### ISSUE TITLE
Does not show images which has size less than 256 px

### ISSUE THREAD

**Issue by varun0922** [greggman/image-grid#1]
It is an awesome library. Thanks for creating it. 
But if you could change the mix size to 10 px so it will be a bast.:)

**Comment by greggman** [comment]
I haven't touched this in years ... but isn't that a setting? According to the readme

[`http://localhost:8080?minSize=10`](http://localhost:8080?minSize=10)

BTW: The follow up project to this is https://mopho-v.org/

**Comment by varun0922** [comment]
Oh yes my bad :+1:)

**Comment by varun0922** [comment]
Oh yes my bad :+1:)
